[programs.localnet]
dap_protocol = "FHigg3vfJmJMcypFbYrk9rZubV6Ap9nbLJPGnDFyFJ3c"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./node_modules/ts-mocha/bin/ts-mocha -t 1000000 tests/unit/*.ts"
